language: python

python:
  - "3.7"

jobs:
  include:
    - stage: "Build Lab 2."
      name: "Run tests for Lab 2"
      python: 3.7
      install:
        - cd ./lab_2/
        - pipenv install
      script: 
    - pipenv run pytest tests/tests.py
    - pipenv run python app.py
    - stage: "Build Lab 3."
      name: "Run Django Server and test it accessibility. Fail to run and test"
      python: 3.7
      install:
        - cd ./lab_3/
        - pipenv install
        - pipenv install requests
        - pipenv install django
      script: bash ./scripts/travis-build.sh
    - stage: "Build Lab 4."
      name: "Build Docker images & Home task"
      services:
        - docker
      install:
        - cd ./lab_4/
      script:
        - docker build -t roffymonsta/lab4:django-travis .
        - docker images
        - echo "Deydara321" | docker login -u "roffymonsta" --password-stdin
        - docker push roffymonsta/lab4:django-travis
    - stage: "Build Lab 5."
      name: "Build and run Docker images via make"
      services:
        - docker
      install:
        - cd ./lab_5/
        - make app
        - make tests
      script:
        - make run
        - make test-app
branches:
  only:
    - master
