version: '3.7'
services:
  app_server:
    build:
      context: .
      dockerfile: Dockerfile
    image: roffymonsta/lab_4:compose-first
    container_name: app_server
    depends_on:
      - app
    ports:
      - 8000:8000
  monitoring:
    build:
      context: .
      dockerfile: DockerFileSecond
    image: roffymonsta/lab_4:compose-second
    container_name: monitoring
    depends_on:
    - app
    network_mode: "host"
